//! Hand-rolled protobuf codec for the messages this crate needs.
//!
//! We hand-roll instead of pulling prost+protoc into the build because the
//! schema set is small (six messages, all primitive-typed) and dropping the
//! protoc dependency keeps `cargo build` working in any clean environment.
//! Wire-compatible with code generated by any standard Protobuf compiler.
//!
//! Schemas covered (see capra_jetson_stack/protos/ for the canonical .proto):
//!   * RoveControl (telemetry pkg) — inbound from teleop
//!   * RoveTelemetry (telemetry pkg) — outbound to teleop
//!   * IK engine: JointState, Twist, JointCommand (forgebot.ik pkg)
//!
//! Field numbers must stay in sync with the .proto files.

use std::convert::TryInto;

// ---- proto wire types --------------------------------------------------

const WT_VARINT: u32 = 0;
const WT_I64: u32 = 1;
const WT_LEN: u32 = 2;
const WT_I32: u32 = 5;

// ---- encode helpers ----------------------------------------------------

fn write_varint(out: &mut Vec<u8>, mut n: u64) {
    while n > 0x7F {
        out.push(((n & 0x7F) as u8) | 0x80);
        n >>= 7;
    }
    out.push((n & 0x7F) as u8);
}

fn write_tag(out: &mut Vec<u8>, field_num: u32, wire_type: u32) {
    write_varint(out, ((field_num << 3) | wire_type) as u64);
}

fn write_float(out: &mut Vec<u8>, field_num: u32, v: f32) {
    if v == 0.0 {
        return;
    }
    write_tag(out, field_num, WT_I32);
    out.extend_from_slice(&v.to_le_bytes());
}

fn write_uint32(out: &mut Vec<u8>, field_num: u32, v: u32) {
    if v == 0 {
        return;
    }
    write_tag(out, field_num, WT_VARINT);
    write_varint(out, v as u64);
}

fn write_uint64(out: &mut Vec<u8>, field_num: u32, v: u64) {
    if v == 0 {
        return;
    }
    write_tag(out, field_num, WT_VARINT);
    write_varint(out, v);
}

fn write_int32(out: &mut Vec<u8>, field_num: u32, v: i32) {
    if v == 0 {
        return;
    }
    write_tag(out, field_num, WT_VARINT);
    // proto3 int32 is varint, sign-extended to 64 bits for negative values.
    write_varint(out, v as u32 as u64);
}

#[allow(dead_code)]
fn write_bool(out: &mut Vec<u8>, field_num: u32, v: bool) {
    if !v {
        return;
    }
    write_tag(out, field_num, WT_VARINT);
    write_varint(out, 1);
}

fn write_string(out: &mut Vec<u8>, field_num: u32, s: &str) {
    write_tag(out, field_num, WT_LEN);
    write_varint(out, s.len() as u64);
    out.extend_from_slice(s.as_bytes());
}

fn write_msg<F: FnOnce(&mut Vec<u8>)>(out: &mut Vec<u8>, field_num: u32, encode: F) {
    let mut sub = Vec::new();
    encode(&mut sub);
    write_tag(out, field_num, WT_LEN);
    write_varint(out, sub.len() as u64);
    out.extend_from_slice(&sub);
}

// ---- decode helpers ----------------------------------------------------

#[derive(Debug)]
pub struct DecodeError;

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "proto decode error")
    }
}
impl std::error::Error for DecodeError {}

fn read_varint(buf: &[u8], pos: &mut usize) -> Result<u64, DecodeError> {
    let mut n: u64 = 0;
    let mut shift = 0;
    loop {
        if *pos >= buf.len() {
            return Err(DecodeError);
        }
        let b = buf[*pos];
        *pos += 1;
        n |= ((b & 0x7F) as u64) << shift;
        if b & 0x80 == 0 {
            return Ok(n);
        }
        shift += 7;
        if shift > 63 {
            return Err(DecodeError);
        }
    }
}

fn read_f32(buf: &[u8], pos: &mut usize) -> Result<f32, DecodeError> {
    if *pos + 4 > buf.len() {
        return Err(DecodeError);
    }
    let v = f32::from_le_bytes(buf[*pos..*pos + 4].try_into().unwrap());
    *pos += 4;
    Ok(v)
}

fn skip_field(buf: &[u8], pos: &mut usize, wire: u32) -> Result<(), DecodeError> {
    match wire {
        WT_VARINT => {
            read_varint(buf, pos)?;
        }
        WT_LEN => {
            let ln = read_varint(buf, pos)? as usize;
            if *pos + ln > buf.len() {
                return Err(DecodeError);
            }
            *pos += ln;
        }
        WT_I32 => *pos += 4,
        WT_I64 => *pos += 8,
        _ => return Err(DecodeError),
    }
    Ok(())
}

// ---- IK engine messages ------------------------------------------------

#[derive(Debug, Default, Clone)]
pub struct NamedFloat {
    pub name: String,
    pub value: f32,
}

#[derive(Debug, Default, Clone)]
pub struct JointState {
    pub joints: Vec<NamedFloat>,
    pub t_us: u64,
}

#[derive(Debug, Default, Clone)]
pub struct Orientation {
    pub yaw: f32,
    pub pitch: f32,
    pub roll: f32,
}

#[derive(Debug, Default, Clone)]
pub struct Vector3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(Debug, Clone, Copy)]
#[repr(u32)]
pub enum IkMode {
    ResolvedRate = 0,
    PositionIk = 1,
}

#[derive(Debug, Default, Clone)]
pub struct Twist {
    pub orientation: Orientation,
    pub position: Vector3,
    pub mode: u32,
    pub t_us: u64,
}

#[derive(Debug, Default, Clone)]
pub struct JointCommand {
    pub joints: Vec<NamedFloat>,
    pub mode: u32,
    pub t_us: u64,
    pub converged: bool,
    pub residual: f32,
}

fn encode_named_float(out: &mut Vec<u8>, nf: &NamedFloat) {
    if !nf.name.is_empty() {
        write_string(out, 1, &nf.name);
    }
    write_float(out, 2, nf.value);
}

pub fn encode_joint_state(js: &JointState) -> Vec<u8> {
    let mut out = Vec::with_capacity(64);
    for nf in &js.joints {
        write_msg(&mut out, 1, |b| encode_named_float(b, nf));
    }
    write_uint64(&mut out, 2, js.t_us);
    out
}

pub fn encode_twist(t: &Twist) -> Vec<u8> {
    let mut out = Vec::with_capacity(48);
    write_msg(&mut out, 1, |b| {
        write_float(b, 1, t.orientation.yaw);
        write_float(b, 2, t.orientation.pitch);
        write_float(b, 3, t.orientation.roll);
    });
    write_msg(&mut out, 2, |b| {
        write_float(b, 1, t.position.x);
        write_float(b, 2, t.position.y);
        write_float(b, 3, t.position.z);
    });
    if t.mode != 0 {
        write_tag(&mut out, 3, WT_VARINT);
        write_varint(&mut out, t.mode as u64);
    }
    write_uint64(&mut out, 4, t.t_us);
    out
}

fn decode_named_float(buf: &[u8]) -> Result<NamedFloat, DecodeError> {
    let mut nf = NamedFloat::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                if pos + ln > buf.len() {
                    return Err(DecodeError);
                }
                nf.name = std::str::from_utf8(&buf[pos..pos + ln])
                    .map_err(|_| DecodeError)?
                    .to_owned();
                pos += ln;
            }
            (2, WT_I32) => {
                nf.value = read_f32(buf, &mut pos)?;
            }
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(nf)
}

pub fn decode_joint_command(buf: &[u8]) -> Result<JointCommand, DecodeError> {
    let mut jc = JointCommand::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                if pos + ln > buf.len() {
                    return Err(DecodeError);
                }
                jc.joints.push(decode_named_float(&buf[pos..pos + ln])?);
                pos += ln;
            }
            (2, WT_VARINT) => {
                jc.mode = read_varint(buf, &mut pos)? as u32;
            }
            (3, WT_VARINT) => {
                jc.t_us = read_varint(buf, &mut pos)?;
            }
            (4, WT_VARINT) => {
                jc.converged = read_varint(buf, &mut pos)? != 0;
            }
            (5, WT_I32) => {
                jc.residual = read_f32(buf, &mut pos)?;
            }
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(jc)
}

// ---- RoveControl (telemetry pkg) - inbound from teleop ----------------

#[derive(Debug, Default, Clone)]
pub struct Tracks {
    pub left_vel: f32,
    pub right_vel: f32,
}

#[derive(Debug, Default, Clone)]
pub struct Flippers {
    pub fl: i32,
    pub fr: i32,
    pub rl: i32,
    pub rr: i32,
}

#[derive(Debug, Default, Clone)]
pub struct OvisTwist {
    pub orientation: Orientation,
    pub position: Vector3,
}

#[derive(Debug, Default, Clone)]
pub struct Gripper {
    pub open_state: bool,
}

#[derive(Debug, Default, Clone)]
pub struct RoveControl {
    pub tracks: Tracks,
    pub flippers: Flippers,
    pub ovis: OvisTwist,
    pub gripper: Gripper,
    pub timestamp_us: u64,
}

fn decode_orientation(buf: &[u8]) -> Result<Orientation, DecodeError> {
    let mut o = Orientation::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_I32) => o.yaw = read_f32(buf, &mut pos)?,
            (2, WT_I32) => o.pitch = read_f32(buf, &mut pos)?,
            (3, WT_I32) => o.roll = read_f32(buf, &mut pos)?,
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(o)
}

fn decode_vector3(buf: &[u8]) -> Result<Vector3, DecodeError> {
    let mut v = Vector3::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_I32) => v.x = read_f32(buf, &mut pos)?,
            (2, WT_I32) => v.y = read_f32(buf, &mut pos)?,
            (3, WT_I32) => v.z = read_f32(buf, &mut pos)?,
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(v)
}

fn decode_tracks(buf: &[u8]) -> Result<Tracks, DecodeError> {
    let mut t = Tracks::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_I32) => t.left_vel = read_f32(buf, &mut pos)?,
            (2, WT_I32) => t.right_vel = read_f32(buf, &mut pos)?,
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(t)
}

fn decode_flippers(buf: &[u8]) -> Result<Flippers, DecodeError> {
    let mut f = Flippers::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        // sint32 uses zig-zag: (n >> 1) ^ -(n & 1)
        if wt == WT_VARINT {
            let raw = read_varint(buf, &mut pos)?;
            let signed = ((raw >> 1) as i64 ^ -((raw & 1) as i64)) as i32;
            match fn_ {
                1 => f.fl = signed,
                2 => f.fr = signed,
                3 => f.rl = signed,
                4 => f.rr = signed,
                _ => {}
            }
        } else {
            skip_field(buf, &mut pos, wt)?;
        }
    }
    Ok(f)
}

fn decode_ovis_twist(buf: &[u8]) -> Result<OvisTwist, DecodeError> {
    let mut ov = OvisTwist::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                if pos + ln > buf.len() {
                    return Err(DecodeError);
                }
                ov.orientation = decode_orientation(&buf[pos..pos + ln])?;
                pos += ln;
            }
            (2, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                if pos + ln > buf.len() {
                    return Err(DecodeError);
                }
                ov.position = decode_vector3(&buf[pos..pos + ln])?;
                pos += ln;
            }
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(ov)
}

fn decode_gripper(buf: &[u8]) -> Result<Gripper, DecodeError> {
    let mut g = Gripper::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        if (fn_, wt) == (1, WT_VARINT) {
            g.open_state = read_varint(buf, &mut pos)? != 0;
        } else {
            skip_field(buf, &mut pos, wt)?;
        }
    }
    Ok(g)
}

pub fn decode_rove_control(buf: &[u8]) -> Result<RoveControl, DecodeError> {
    let mut rc = RoveControl::default();
    let mut pos = 0;
    while pos < buf.len() {
        let tag = read_varint(buf, &mut pos)?;
        let fn_ = (tag >> 3) as u32;
        let wt = (tag & 7) as u32;
        match (fn_, wt) {
            (1, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                rc.tracks = decode_tracks(&buf[pos..pos + ln])?;
                pos += ln;
            }
            (2, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                rc.flippers = decode_flippers(&buf[pos..pos + ln])?;
                pos += ln;
            }
            (3, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                rc.ovis = decode_ovis_twist(&buf[pos..pos + ln])?;
                pos += ln;
            }
            (4, WT_LEN) => {
                let ln = read_varint(buf, &mut pos)? as usize;
                rc.gripper = decode_gripper(&buf[pos..pos + ln])?;
                pos += ln;
            }
            (5, WT_VARINT) => {
                rc.timestamp_us = read_varint(buf, &mut pos)?;
            }
            _ => skip_field(buf, &mut pos, wt)?,
        }
    }
    Ok(rc)
}

// ---- RoveTelemetry (telemetry pkg) - outbound to teleop ----------------

#[derive(Debug, Default, Clone)]
pub struct DriveNodeState {
    pub node_id: u32,
    pub node_state: u32,
    pub node_temp_c: f32,
    pub motor_temp_c: f32,
    pub motor_amp: f32,
    pub motor_pos: f32,
    pub active_errors: i32,
    pub latched_errors: i32,
}

#[derive(Debug, Default, Clone)]
pub struct OvisTelemetry {
    pub act_1: DriveNodeState,
    pub act_2: DriveNodeState,
    pub act_3: DriveNodeState,
    pub act_4: DriveNodeState,
    pub act_5: DriveNodeState,
    pub act_6: DriveNodeState,
}

#[derive(Debug, Default, Clone)]
pub struct RoveTelemetry {
    pub ovis: OvisTelemetry,
    pub timestamp_us: u64,
    pub machine_state: u32,
}

fn encode_drive_node_state(out: &mut Vec<u8>, d: &DriveNodeState) {
    write_uint32(out, 1, d.node_id);
    write_uint32(out, 2, d.node_state);
    write_float(out, 3, d.node_temp_c);
    write_float(out, 4, d.motor_temp_c);
    write_float(out, 5, d.motor_amp);
    write_float(out, 6, d.motor_pos);
    write_int32(out, 7, d.active_errors);
    write_int32(out, 8, d.latched_errors);
}

fn encode_ovis_telemetry(out: &mut Vec<u8>, ov: &OvisTelemetry) {
    write_msg(out, 1, |b| encode_drive_node_state(b, &ov.act_1));
    write_msg(out, 2, |b| encode_drive_node_state(b, &ov.act_2));
    write_msg(out, 3, |b| encode_drive_node_state(b, &ov.act_3));
    write_msg(out, 4, |b| encode_drive_node_state(b, &ov.act_4));
    write_msg(out, 5, |b| encode_drive_node_state(b, &ov.act_5));
    write_msg(out, 6, |b| encode_drive_node_state(b, &ov.act_6));
}

pub fn encode_rove_telemetry(t: &RoveTelemetry) -> Vec<u8> {
    let mut out = Vec::with_capacity(256);
    // Field 1 (odrives), 3 (vn300), 4 (battery) intentionally omitted —
    // this wrapper only knows about the kinova arm. Receivers tolerate
    // missing optional message fields.
    write_msg(&mut out, 2, |b| encode_ovis_telemetry(b, &t.ovis));
    write_uint64(&mut out, 5, t.timestamp_us);
    write_uint32(&mut out, 6, t.machine_state);
    out
}
