[package]
name = "udp_multiplexer"
version = "0.1.0"
edition = "2021"

[lib]
name = "udp_multiplexer"
path = "src/lib.rs"

[[bin]]
name = "udp_multiplexer"
path = "src/main.rs"

[[bin]]
name = "test_rove_control"
path = "src/tests/test_rove_control.rs"

[[bin]]
name = "test_rove_telemetry"
path = "src/tests/test_rove_telemetry.rs"

[dependencies]
prost = "0.13"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[build-dependencies]
prost-build = "0.13"