[[config]]
path_to_protobuf = "src/proto/"
emit_interval_ms = 50
staleness_ms = 500

[[inputs]]
address = "192.168.2.44:5005"
priority = 1
protobuf = "RoveControl.proto"

[[inputs]]
address = "127.0.0.1:5051"
priority = 2
protobuf = "RoveControl.proto"

[[outputs]]
address = "127.0.0.1:9000"
protobuf = "RoveControl.proto"